version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PG_HOST: "db"
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./logs:/logs/
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
      
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    restart: always
    volumes:
      - ./initdb/init-notes.sql:/docker-entrypoint-initdb.d/init-notes.sql
    ports:
      - "54344:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 10
